# Generated by Django 4.1.5 on 2023-01-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermadiate", "Intermadiate"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="")),
            ],
        ),
    ]
